spring.application.name=app
   spring.datasource.url=jdbc:mysql://localhost:3306/sapms_app_db
   spring.datasource.username=sapms_app_user
   spring.datasource.password=sapms_app_123
   spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

   spring.jpa.hibernate.ddl-auto=validate
   spring.jpa.show-sql=true
   spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

   spring.flyway.enabled=true
   spring.flyway.locations=classpath:db/migration
   spring.flyway.baseline-on-migrate=true
   spring.flyway.validate-on-migrate=true
   spring.flyway.clean-disabled=true

   app.jwt.secret=c3VwZXJzZWNyZXRrZXlmb3Jqd3RzdXBlcnNlY3JldGtleWZvcmp3dG1pbjMyY2hhcnM=
   app.jwt.expiration=86400000
   app.jwt.refresh-expiration=604800000

   spring.mail.host=smtp.gmail.com
   spring.mail.port=587
   spring.mail.username=mikimeba2023@gmail.com
   spring.mail.password=pwdjpnidxlnrpjyu
   spring.mail.properties.mail.smtp.auth=true
   spring.mail.properties.mail.smtp.starttls.enable=true
   spring.mail.properties.mail.smtp.starttls.required=true
   spring.mail.properties.mail.smtp.connectiontimeout=5000
   spring.mail.properties.mail.smtp.timeout=5000
   spring.mail.properties.mail.smtp.writetimeout=5000

   springdoc.api-docs.path=/v3/api-docs
   springdoc.swagger-ui.path=/swagger-ui.html
   springdoc.swagger-ui.operationsSorter=method
   springdoc.swagger-ui.tagsSorter=alpha
   springdoc.swagger-ui.display-request-duration=true
   springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
   springdoc.swagger-ui.url=/v3/api-docs
   springdoc.pathsToMatch=/api/**
   springdoc.packagesToScan=com.hopesapms.app.controller
   springdoc.swagger-ui.csrf.enabled=false

   logging.level.org.springframework=DEBUG
   logging.level.org.springdoc=DEBUG